### ISSUE TITLE
0xApes

### ISSUE THREAD

**Issue by KetaWas** [ba1lly/Pearls#38]
![0xRed923](https://user-images.githubusercontent.com/86163426/169413898-f5b2e996-b1d2-45ce-885d-fcf5dece4685.png)

**Comment by Crypto-Alchemist** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/104940729/169415004-cd973c85-7134-41f5-84fc-5463fc1dfe0f.png)

**Comment by Crypto-Alchemist** [comment]
![unnamed (4)](https://user-images.githubusercontent.com/104940729/169415025-3b0c0b2d-9d73-4230-8a4d-c6d30fc87a91.png)

**Comment by Crypto-Alchemist** [comment]
![unnamed (3)](https://user-images.githubusercontent.com/104940729/169415049-555c0bba-4a2a-47ef-944a-b73ffb541a97.png)

**Comment by Crypto-Alchemist** [comment]
![unnamed (2)](https://user-images.githubusercontent.com/104940729/169415062-5e999ccd-4bf8-4390-9b35-a6a62fe391a1.png)

**Comment by KetaWas** [comment]
enough

**Comment by funkymonkey5150** [comment]
I do apologize my ignorance what is this 
I would like to know if this is ongoiong oproject
