### ISSUE TITLE
bulltater

### ISSUE THREAD

**Issue by KetaWas** [ba1lly/Pearls#42]
![bulltater](https://user-images.githubusercontent.com/86163426/169415036-e9fc047a-5c6b-4d40-9dbe-9d5912cfdf11.jpg)

**Comment by ba1lly** [comment]
![QmTroxR36V1VZy7WrjKhdxERzBcyhXCNXanmuZ6rJbfMa6](https://user-images.githubusercontent.com/99600762/169415217-959a79ac-1701-4e09-a1d9-984e656a3902.jpg)

**Comment by KetaWas** [comment]
goood good should we not close it
